prometheus:
  user: prometheus
  group: prometheus
  server:
    version: 1.4.1.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/prometheus/releases/download/v1.4.1/prometheus-1.4.1.linux-amd64.tar.gz
    source_hash: sha1=3e78173e7d65623e79e0292da16e6155de947185
    args:
      config_file: /etc/prometheus/prometheus.yml
      storage:
        local_path: /var/lib/prometheus/metrics
  alertmanager:
    version: 0.11.0.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/alertmanager/releases/download/v0.11.0/alertmanager-0.11.0.linux-amd64.tar.gz
    source_hash: sha256=006fe10659bebe5a625eaf2fac46eb8cf5610b4cd9b6a25238f77c6173c05166
    args:
      config.file: /etc/alertmanager/alertmanager.yml
      storage.path: /var/lib/alertmanager
  pushgateway:
    version: 0.4.0.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/pushgateway/releases/download/v0.4.0/pushgateway-0.4.0.linux-amd64.tar.gz
    source_hash: sha256=e1ce58b3f2c44816e748278434d6fc91e530da77dcc34b1246e1a0f25314831f
    config: {}
    args:
      config_file: /etc/pushgateway/pushgateway.yml
      storage:
        path: /var/lib/pushgateway
  exporters:
    node:
      version: 0.13.0.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/node_exporter/releases/download/v0.13.0/node_exporter-0.13.0.linux-amd64.tar.gz
      source_hash: sha1=84ca5f711962319f6f7823208b9d867ab1c0e3e7
    blackbox:
      version: 0.3.0.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/blackbox_exporter/releases/download/v0.3.0/blackbox_exporter-0.3.0.linux-amd64.tar.gz
      source_hash: sha1=89ac98c062315ba35eda257ca88c8c4b43f38d47
      args:
        config_file: /etc/prometheus/blackbox_exporter.yml
    haproxy:
      version: 0.7.1.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/haproxy_exporter/releases/download/v0.7.1/haproxy_exporter-0.7.1.linux-amd64.tar.gz
      source_hash: sha1=56849253e280db3db2aa80f1013ecfe242536d32
      args:
        scrape_uri: 'unix:/run/haproxy/admin.sock'
    rabbitmq:
      version: 0.24.0.linux-amd64
      install_dir: /opt
      source: https://github.com/kbudde/rabbitmq_exporter/releases/download/v0.24.0/rabbitmq_exporter-0.24.0.linux-amd64.tar.gz
      source_hash: sha256=dbbd44a5a4b4a22ba338b9732c014587bc11513a5d6d2e3e519fc313b1cc46d4
      config: |
        RABBIT_CAPABILITIES=no_sort,bert
    riak:
      source: git+https://github.com/anti1869/riak_exporter.git
      args:
        address: 0.0.0.0
        port: 9197
        riak: http://localhost:8098/stats
        endpoint: /metrics
    postgres:
      install_dir: /opt
      version: v0.4.1_linux-amd64
      source: https://github.com/wrouesnel/postgres_exporter/releases/download/v0.4.1/postgres_exporter_v0.4.1_linux-amd64.tar.gz
      source_hash: sha256=219c2c116cb496d54ddbd23f392a38c3496ab8e7118dfbf8b7c0b21593dedbfd
      args: ''
    solr:
      version: 0.0.12.linux-amd64
      install_dir: /opt
      source: https://github.com/noony/prometheus-solr-exporter/releases/download/v0.0.12/prometheus-solr-exporter-0.0.12.linux-amd64.tar.gz
      source_hash: sha256=58877e5cf04b981129bca7995bf207979c686ee76fefd21ba1d9858d1caf4494
      args:
        scrape_uri: 'unix:/run/haproxy/admin.sock'
    redis:
      version: 0.17.2.linux-amd64
      source: https://github.com/oliver006/redis_exporter/releases/download/v0.17.2/redis_exporter-v0.17.2.linux-amd64.tar.gz
      install_dir: /opt
      args: ''
